name: "Go Test"
on:
  push:
    branches:
      - main
      - test
    paths:
      - se_go/**
  pull_request:
    branches:
      - main
    types: [closed]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: se_go
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...